// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PravoTech.Articles.Data;

#nullable disable

namespace PravoTech.Articles.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250618090159_AddPerformanceIndexes")]
    partial class AddPerformanceIndexes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ArticleTag", b =>
                {
                    b.Property<Guid>("ArticlesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TagsId")
                        .HasColumnType("int");

                    b.HasKey("ArticlesId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("ArticleTag");
                });

            modelBuilder.Entity("PravoTech.Articles.Entities.Article", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid?>("SectionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Articles_CreatedAt");

                    b.HasIndex("EffectiveDate")
                        .HasDatabaseName("IX_Articles_EffectiveDate");

                    b.HasIndex("SectionId");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("IX_Articles_UpdatedAt");

                    b.ToTable("Articles");
                });

            modelBuilder.Entity("PravoTech.Articles.Entities.ArticleTag", b =>
                {
                    b.Property<Guid>("ArticleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.HasKey("ArticleId", "TagId");

                    b.HasIndex("TagId")
                        .HasDatabaseName("IX_ArticleTags_TagId");

                    b.HasIndex("ArticleId", "Order")
                        .IsUnique()
                        .HasDatabaseName("IX_ArticleTags_ArticleId_Order");

                    b.ToTable("ArticleTags");
                });

            modelBuilder.Entity("PravoTech.Articles.Entities.Section", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Sections_Name");

                    b.ToTable("Sections");
                });

            modelBuilder.Entity("PravoTech.Articles.Entities.SectionTag", b =>
                {
                    b.Property<Guid>("SectionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.HasKey("SectionId", "TagId");

                    b.HasIndex("TagId")
                        .HasDatabaseName("IX_SectionTags_TagId");

                    b.ToTable("SectionTags");
                });

            modelBuilder.Entity("PravoTech.Articles.Entities.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Tags_Name");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("IX_Tags_NormalizedName");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("SectionTag", b =>
                {
                    b.Property<Guid>("SectionsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TagsId")
                        .HasColumnType("int");

                    b.HasKey("SectionsId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("SectionTag");
                });

            modelBuilder.Entity("ArticleTag", b =>
                {
                    b.HasOne("PravoTech.Articles.Entities.Article", null)
                        .WithMany()
                        .HasForeignKey("ArticlesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PravoTech.Articles.Entities.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PravoTech.Articles.Entities.Article", b =>
                {
                    b.HasOne("PravoTech.Articles.Entities.Section", null)
                        .WithMany("Articles")
                        .HasForeignKey("SectionId");
                });

            modelBuilder.Entity("PravoTech.Articles.Entities.ArticleTag", b =>
                {
                    b.HasOne("PravoTech.Articles.Entities.Article", "Article")
                        .WithMany("ArticleTags")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PravoTech.Articles.Entities.Tag", "Tag")
                        .WithMany("ArticleTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("PravoTech.Articles.Entities.SectionTag", b =>
                {
                    b.HasOne("PravoTech.Articles.Entities.Section", "Section")
                        .WithMany("SectionTags")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PravoTech.Articles.Entities.Tag", "Tag")
                        .WithMany("SectionTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Section");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("SectionTag", b =>
                {
                    b.HasOne("PravoTech.Articles.Entities.Section", null)
                        .WithMany()
                        .HasForeignKey("SectionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PravoTech.Articles.Entities.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PravoTech.Articles.Entities.Article", b =>
                {
                    b.Navigation("ArticleTags");
                });

            modelBuilder.Entity("PravoTech.Articles.Entities.Section", b =>
                {
                    b.Navigation("Articles");

                    b.Navigation("SectionTags");
                });

            modelBuilder.Entity("PravoTech.Articles.Entities.Tag", b =>
                {
                    b.Navigation("ArticleTags");

                    b.Navigation("SectionTags");
                });
#pragma warning restore 612, 618
        }
    }
}
